- name: Download Butane binary (amd64)
  ansible.builtin.get_url:
    url: '{{ butane_url_amd64 }}'
    dest: /tmp/butane
    mode: '0755'
  when: ansible_architecture == "x86_64"

- name: Download Butane binary (aarch64)
  ansible.builtin.get_url:
    url: '{{ butane_url_aarch64 }}'
    dest: /tmp/butane
    mode: '0755'
  when:
    - ( ansible_facts.architecture is search("arm") and
        ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")

- name: Get Butane/Ignition file path
  ansible.builtin.set_fact:
    butane_path: '{{ (hypervisor == "libvirt") | ansible.builtin.ternary("/var/lib/libvirt/butane", "/var/lib/vz/snippets") }}'

- name: Create Butane config directory
  ansible.builtin.file:
    path: '{{ butane_path }}'
    state: directory
    owner: root
    group: kvm
    mode: '0770'
  become: true
  when: hypervisor == 'libvirt'

- name: Generate Butane config
  ansible.builtin.template:
    src: templates/fcos.bu.j2
    dest: '/tmp/{{ item.hostname }}.bu'
    mode: '0660'
    owner: root
    group: kvm
  loop: '{{ nodes }}'
  become: true

- name: Generate Ignition config
  ansible.builtin.shell: /tmp/butane < /tmp/{{ item.hostname }}.bu > {{ item.hostname }}.ign
  changed_when: true
  args:
    chdir: '{{ butane_path }}'
  loop: '{{ nodes }}'
  become: true

- name: Change Ignition config owner and permissions
  ansible.builtin.file:
    path: '{{ butane_path }}/{{ item.hostname }}.ign'
    owner: root
    group: kvm
    mode: '0660'
  loop: '{{ nodes }}'
  become: true
