apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: apps-homelab
  labels:
    name: tailscale
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  destination:
    server: https://homelab-k8s-operator.lobster-altair.ts.net
    namespace: tailscale
  sources:
    - chart: tailscale-operator
      repoURL: https://pkgs.tailscale.com/helmcharts
      targetRevision: 1.90.9
      helm:
        valueFiles:
          - $values/k8s/homelab/network/tailscale/values.yaml
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      path: k8s/homelab/network/tailscale/resources
      ref: values
  ignoreDifferences:
    - kind: Service
      namespace: tailscale
      jsonPointers:
        - /spec/externalName
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/audit-version: latest
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/warn-version: latest
    syncOptions:
      - CreateNamespace=true
