---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: curseforge-api
  namespace: minecraft
spec:
  encryptedData:
    cf-api-key: AgCRGrIdR4dscAXXl2pHvT55KOj9zXkam83JrYTpGkW+7D8a8uavp0FzZM8vpph7BsXdgALzsowWZqobcqFgOVzX+nZMpvB/b7rBXytq6Ti78bE7yKDYaE8rwKGewLnW1UlypWopovcgOfinV7/qahSop7SD4yvp1xvWNXnGibsO1iyYtYxzpn+8AUWcvNCyFY+LMdyjJ+l6pGT/ht0WOLlVMan9cavqQTPmIH0VBhYufiJERFlNx+BHy4kWvNoPGw5SxtH2Zi2jypsYhoTfcJiMSv3QBUdU+LBGGrh1dgypNzqALg9CKVlRVorWqRmurT9gshM2R4lK96dmffY7owEgcSDxGjr7TqzN443Pi6sGySfAyJO8mdbnCK+nIUkaV4adVAhE2bV2kRG+8QMUGm+xyeroriJHuA7CvTmYG+097iBcBeZkh7yKUxAC/nxjoWsqWi7dG2IRrKUvzMlX8e67mz25VHP/JkL4VhuC5o32kLcNxdjOsq755nRKcEHYcofQOgnMmmae7D4/3fySYjzorb2Mtl59HRBUw17fqscdlYlSG5vBT+NlIKdknlf3iLvGLsS41DeOzSmfdcC6rjHIkuJD1aPdHlSvHhC+ELzeHmQCiHQa9e0hnQXWpivD/o8zAiJxyP/DS7Mt8UZlUbuYsvOAOGvcbeuXMDRme+HtNId78oNDrfPJoato0o+LTZ3xodCR/62yeYec+VkO0/DhsiJ8W1HuRMb08Qcaz6vdLezg+ZXOR934NAs8g+9V61Vp/iq6CEx09x/gAlA=
  template:
    metadata:
      name: curseforge-api
      namespace: minecraft
    type: Opaque
