node_ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGyDxmy1/0RfNrOVDeYjL6VypWhDU3cfjIbORDG3MoTW liquid@liquid-desktop

image_downloads:
  amd64:
    url: https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/42.20250721.3.0/x86_64/fedora-coreos-42.20250721.3.0-proxmoxve.x86_64.qcow2.xz
    checksum: sha256:80bc3a4b6569ce7c6f9f9f1f5f23fc614813947cc274a3946302541271c88413
  aarch64:
    url: https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/40.20240906.3.0/aarch64/fedora-coreos-40.20240906.3.0-qemu.aarch64.qcow2.xz
    checksum: sha256:0beea26fd9baef60971fb83eb9ddf8b4c1991448540a5d6bf2fd91a64758d9fa
