proxmox_username: "{{ lookup('community.general.onepassword', 'vkpctqrzenumupwfmpdmmfcow4', field='username') }}@pam"
proxmox_password: "{{ lookup('community.general.onepassword', 'vkpctqrzenumupwfmpdmmfcow4', field='password') }}"
