- name: Get path for image download
  ansible.builtin.set_fact:
    # downloading the image to /root instead of /tmp on Proxmox
    # to avoid accidentally triggering the OOM killer
    image_tmp_path: '{{ (hypervisor == "libvirt") | ansible.builtin.ternary("/tmp/", "/root") }}/fcos.img'

- name: Check if the image is downloaded
  ansible.builtin.stat:
    path: '{{ image_tmp_path }}'
  register: image

- name: Download Fedora CoreOS image
  when: not image.stat.exists
  block:
    - ansible.builtin.include_tasks: amd64.yaml
      when: ansible_architecture == "x86_64"

    - ansible.builtin.include_tasks: arm64.yaml
      when:
        - ( ansible_facts.architecture is search("arm") and
            ansible_facts.userspace_bits == "64" ) or
          ansible_facts.architecture is search("aarch64")

    - name: Extract image
      ansible.builtin.command: 'xz --decompress {{ image_tmp_path }}.xz'
      args:
        creates: '{{ image_tmp_path }}'
