apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: apps-homelab
  labels:
    name: sonarr
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://homelab-k8s-operator.lobster-altair.ts.net
    namespace: media
  project: homelab
  sources:
    - chart: app-template
      repoURL: ghcr.io/bjw-s-labs/helm
      targetRevision: 4.6.2
      helm:
        valueFiles:
          - $values/k8s/homelab/media/sonarr/values.yaml
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      path: k8s/homelab/media/sonarr/resources
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
