apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - serviceaccount.yaml
  - networkpolicy.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: glance-k8s
  - includeTemplates: true
    pairs:
      app.kubernetes.io/version: v0.4.0
images:
  - name: ghcr.io/lukasdietrich/glance-k8s/chart/glance-k8s
    newTag: v0.4.0@sha256:7016ef6068b93c86b0d8e37130d1761a6b169812f25b7b603b39bece5ef6344b
