apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: apps-luna
  labels:
    name: authentik
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  project: luna
  sources:
    - chart: authentik
      repoURL: ghcr.io/goauthentik/helm-charts
      targetRevision: 2025.12.3
      helm:
        valueFiles:
          - $values/k8s/luna/authentik/values.yaml
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      path: k8s/luna/authentik/resources
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
