apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: glance
  - includeTemplates: true
    pairs:
      app.kubernetes.io/part-of: glance
resources:
  - base
  - glance-k8s
