apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plugin-barman-cloud
  namespace: apps-homelab
  labels:
    name: plugin-barman-cloud
spec:
  project: homelab
  destination:
    server: https://homelab-k8s-operator.lobster-altair.ts.net
    namespace: cnpg-system
  sources:
    - chart: plugin-barman-cloud
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.4.0
      helm:
        valuesObject:
          certificate:
            renewBefore: 720h
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
