image:
  repository: deluan/navidrome
  tag: 0.60.3

controller:
  annotations:
    glance/id: navidrome
    glance/name: Navidrome
    glance/description: Music streaming
    glance/icon: di:navidrome
    glance/category: media

env:
  ND_BASEURL: https://navidrome.hs.liquid.sh
  ND_PROMETHEUS_ENABLED: 'true'
  ND_PASSWORDENCRYPTIONKEY:
    valueFrom:
      secretKeyRef:
        name: navidrome
        key: passwordEncryptionKey

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch
  seccompProfile:
    type: RuntimeDefault

service:
  main:
    monitor:
      enabled: true
      endpoints:
        - port: http
          scheme: http
          path: /metrics
          interval: 10s

persistence:
  config:
    enabled: true
    storageClass: longhorn
    size: 250Mi
  music:
    enabled: true
    existingClaim: navidrome-media
  tmp:
    enabled: true
    type: emptyDir
