apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-common
  namespace: apps-homelab
  labels:
    name: minecraft-common
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://homelab-k8s-operator.lobster-altair.ts.net
    namespace: minecraft
  project: homelab
  sources:
    - repoURL: https://github.com/LiquidPL/infra.git
      targetRevision: master
      path: k8s/homelab/gameservers/minecraft/common
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - CreateNamespace=true
