apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-upload
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
    immich-volume: upload
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Ti
  nfs:
    server: truenas.hs.liquid.sh
    path: "/mnt/pool/immich/upload"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-upload
spec:
  storageClassName: ''
  selector:
    matchLabels:
      immich-volume: upload
      app.kubernetes.io/name: immich
      app.kubernetes.io/instance: immich
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-external
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
    immich-volume: external
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  nfs:
    server: truenas.hs.liquid.sh
    path: "/mnt/pool/immich/external"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-external
spec:
  storageClassName: ''
  selector:
    matchLabels:
      immich-volume: external
      app.kubernetes.io/name: immich
      app.kubernetes.io/instance: immich
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
