apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: apps-luna
  labels:
    name: cnpg
spec:
  project: luna
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  sources:
    - chart: cloudnative-pg
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.27.1
      helm:
        valuesObject:
          config:
            data:
              ENABLE_INSTANCE_MANAGER_INPLACE_UPDATES: 'true'
              INHERITED_ANNOTATIONS: glance/parent
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 128Mi
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 3
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
