config: |
  # TODO: configure auth and tls once the helm chart is updated to support 0.14
  auth:
    enabled: false
  tls:
    enabled: false
  mqtt:
    enabled: true
    host: 10.10.0.200
    user: '{FRIGATE_MQTT_USER}'
    password: '{FRIGATE_MQTT_PASSWORD}'
  detectors:
    ov:
      type: openvino
      device: GPU
  model:
    width: 300
    height: 300
    input_tensor: nhwc
    input_pixel_format: bgr
    path: /openvino-model/ssdlite_mobilenet_v2.xml
    labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  go2rtc:
    streams:
      driveway:
        - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.10.10.11:554/cam/realmonitor?channel=1&subtype=0
      driveway_sub:
        - 'ffmpeg:driveway#video=h264#width=1280#height=720#raw=-fpsmax 5#hardware=vaapi'
      backyard:
        - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.10.10.10:554/cam/realmonitor?channel=1&subtype=0
      backyard_sub:
        - 'ffmpeg:backyard#video=h264#width=1280#height=720#raw=-fpsmax 5#hardware=vaapi'
    webrtc:
      candidates:
        - 10.10.100.254:8555
        - 100.118.30.9:8555
        - stun:8555
      ice_servers:
        - urls: [stun:stun.l.google.com:19302]
  ffmpeg:
    hwaccel_args: preset-intel-qsv-h264
  cameras:
    driveway:
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/driveway
            input_args: preset-rtsp-restream
            roles:
              - record
          - path: rtsp://127.0.0.1:8554/driveway_sub
            input_args: preset-rtsp-restream
            roles:
              - detect
      detect:
        enabled: true
        width: 1280
        height: 720
      motion:
        mask:
          - 0.753,0.043,0.753,0.08,0.964,0.081,0.963,0.037
          - 0.521,0.515,0.517,0.603,0.634,0.861,0.698,0.877,0.727,0.888,0.745,0.856,0.744,0.771,0.716,0.659,0.688,0.63,0.659,0.593,0.619,0.545,0.601,0.496,0.558,0.478
          - 0.3,0.183,0.337,0.268,0.352,0.271,0.378,0.29,0.414,0.282,0.425,0.29,0.438,0.261,0.433,0.234,0.407,0.197,0.383,0.154,0.368,0.156,0.355,0.137,0.343,0.142,0.322,0.15
          - 0,0.52,0.111,0.618,0.084,0.733,0.088,0.796,0.081,0.896,0.051,0.913,0.021,0.896,0.001,0.864
          - 0.811,0,0.798,0.032,0.791,0.113,0.766,0.156,0.757,0.221,0.757,0.274,0.78,0.258,0.798,0.214,0.825,0.215,0.858,0.232,0.885,0.253,0.88,0.298,0.89,0.347,0.898,0.369,0.891,0.41,0.906,0.441,0.901,0.486,0.912,0.499,0.933,0.471,0.945,0.486,0.944,0.515,0.938,0.546,0.943,0.579,0.962,0.583,0.986,0.621,1,0.662,1,0
      objects:
        track:
          - person
          - car
      record:
        enabled: true
        retain:
          days: 7
          mode: all
        events:
          retain:
            default: 14
            mode: active_objects
    backyard:
      ffmpeg:
        inputs:
          - path: rtsp://127.0.0.1:8554/backyard
            input_args: preset-rtsp-restream
            roles:
              - record
          - path: rtsp://127.0.0.1:8554/backyard_sub
            input_args: preset-rtsp-restream
            roles:
              - detect
      detect:
        enabled: true
        width: 1280
        height: 720
      motion:
        mask:
          - 0.754,0.038,0.963,0.036,0.963,0.079,0.753,0.081
          - 1,0.501,0.442,0.427,0.159,0.374,0,0.336,0,0.293,0.234,0.345,0.553,0.401,1,0.467
          - 0.272,0.092,0.29,0.062,0.305,0.071,0.316,0.023,0.335,0.029,0.343,0.042,0.363,0.045,0.378,0.064,0.393,0.09,0.415,0.115,0.406,0.136,0.413,0.158,0.408,0.172,0.405,0.196,0.403,0.234,0.385,0.261,0.369,0.267,0.334,0.261,0.317,0.26,0.303,0.232,0.297,0.193,0.292,0.158,0.269,0.122
          - 0.151,0,0.15,0.067,0.162,0.083,0.161,0.113,0.154,0.135,0.139,0.151,0.155,0.165,0.158,0.191,0.143,0.223,0.129,0.239,0.147,0.27,0.146,0.29,0.141,0.319,0.129,0.354,0.141,0.392,0.127,0.422,0.108,0.447,0.102,0.473,0.114,0.489,0.116,0.518,0.109,0.562,0.099,0.593,0.1,0.636,0.084,0.644,0.07,0.636,0.068,0.656,0.079,0.701,0.055,0.693,0.044,0.704,0.051,0.739,0.052,0.768,0.028,0.763,0.016,0.733,0.006,0.749,0,0.772,0,0
          - 0.562,0.229,0.564,0.179,0.579,0.183,0.581,0.159,0.596,0.154,0.6,0.174,0.614,0.173,0.619,0.188,0.628,0.206,0.631,0.223
      record:
        enabled: true
        retain:
          days: 7
          mode: all
        events:
          retain:
            default: 14
            mode: active_objects
image:
  tag: 0.14.1
persistence:
  media:
    enabled: true
    size: 650Gi
    storageClass: nfs-csi
    skipuninstall: true
  config:
    enabled: true
    size: 512Mi
    storageClass: longhorn
    skipuninstall: true
securityContext:
  capabilities:
    add:
      - PERFMON
resources:
  limits:
    gpu.intel.com/i915: 100
envFromSecrets:
  - frigate-secrets
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: frigate.hs.liquid.sh
      paths: ["/"]
  tls:
    - hosts:
        - frigate.hs.liquid.sh
      secretName: tls-frigate-ingress
